### PR TITLE
Fixes for minecraft client 1.16.1 on FreeBSD12.1

### PR DESCRIPTION
**Pull request by patrickSpaceSurfer**
Fixes to get minecraft client 1.16.1 to work on FreeBSD12.1-RELEASE-p6 amd64

### CODE REVIEW

**Comment by graemeg** [comment]
Is there any chance of getting these changes merged back into the official LWJGL or into FreeBSD's repo (whichever is required)?

**Comment by patrickSpaceSurfer** [comment]
> Is there any chance of getting these changes merged back into the official LWJGL or into FreeBSD's repo (whichever is required)?

The fixes are for minecraft only, they do not fix the LWJGL build for freebsd.

**Comment by cypher386** [comment]
I can't seem to get this to work.  Maybe I'm unclear on the documentation.  I installed GCC, cleaned, rebuilt and ran, the Launcher.jar with the provided script, but it throws an error upon trying to load the library.
"ava.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl_tinyfd.so
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.util.tinyfd.TinyFileDialogs.<clinit>(TinyFileDialogs.java:37)
	at dgy.b(SourceFile:215)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1666)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1847)
	at dgy.<init>(SourceFile:90)
	at ecn.a(SourceFile:21)
	at dlx.<init>(SourceFile:449)
	at net.minecraft.client.main.Main.main(SourceFile:177)
"
I don't know if its trying to download the linux native libraries instead of the local overrides or what, I can probably figure that out, but seems like an obvious documentation issue, if I'm missing a step.

**Comment by patrickSpaceSurfer** [comment]
Are you using
https://github.com/patrickSpaceSurfer/lwjgl3-port
I forked this repo because its not longer being actively maintained
My fork should be more up to date

**Comment by cypher386** [comment]
Yes, I'm using your port.

remote.origin.url=https://github.com/patrickSpaceSurfer/lwjgl3-port.git

But what is confusing me is the error message is about tinyfd.so when it
doesn't appear that tinyfd.so is built.

The jar file is build in:

find . -name  *tinyfd*
./lwjgl3/.idea/modules/lwjgl/tinyfd.iml
./lwjgl3/.idea/modules/templates/tinyfd-templates.iml
./lwjgl3/bin/RELEASE/lwjgl-tinyfd
./lwjgl3/bin/RELEASE/lwjgl-tinyfd/lwjgl-tinyfd-javadoc.jar
./lwjgl3/bin/RELEASE/lwjgl-tinyfd/tinyfd_license.txt
./lwjgl3/bin/RELEASE/lwjgl-tinyfd/lwjgl-tinyfd-sources.jar
./lwjgl3/bin/RELEASE/lwjgl-tinyfd/lwjgl-tinyfd.jar
./lwjgl3/bin/classes/templates/tinyfd
./lwjgl3/bin/classes/lwjgl/tinyfd
./lwjgl3/bin/classes/lwjgl/tinyfd/org/lwjgl/util/tinyfd
./lwjgl3/modules/lwjgl/tinyfd
./lwjgl3/modules/lwjgl/tinyfd/tinyfd_license.txt
./lwjgl3/modules/lwjgl/tinyfd/src/templates/kotlin/tinyfd
./lwjgl3/modules/lwjgl/tinyfd/src/generated/c/org_lwjgl_util_tinyfd_TinyFileDialogs.c
./lwjgl3/modules/lwjgl/tinyfd/src/generated/java/org/lwjgl/util/tinyfd
./lwjgl3/modules/samples/src/test/java/org/lwjgl/demo/util/tinyfd

Maybe there is a build log error I'm missing.

**Comment by patrickSpaceSurfer** [comment]
I'm afraid I cannot reproduce this, when I run minecraft it doesn't load any liblwjgl_tinyfd.so library.

Below is an lsof of my running minecraft

COMMAND   PID USER   FD   TYPE                DEVICE SIZE/OFF    NODE NAME
java    13596  pim  cwd   VDIR  3863829994,528604845       22 1540167 /mnt/data/home/pim/.minecraft
java    13596  pim  rtd   VDIR 3256349577,2530598579       30       4 /
java    13596  pim    0u  PIPE    0xfffff8029da10be0    16384         ->0xfffff8029da10d48
java    13596  pim    1u  PIPE    0xfffff8036a274460        0         ->0xfffff8036a2742f8
java    13596  pim    2u  PIPE    0xfffff8036a274460        0         ->0xfffff8036a2742f8
java    13596  pim    3r  VREG 1391721247,4214480561 65548183  366516 /usr/local/openjdk8/jre/lib/rt.jar
java    13596  pim    4r  VREG  3863829994,528604845    15817 1540283 /mnt/data/home/pim/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
java    13596  pim    5r  VREG  3863829994,528604845    30973 1540296 /mnt/data/home/pim/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
java    13596  pim    6r  VREG  3863829994,528604845  1091208 1540359 /mnt/data/home/pim/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
java    13596  pim    7r  VREG  3863829994,528604845   913436 1540287 /mnt/data/home/pim/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
java    13596  pim    8r  VREG  3863829994,528604845 12935630 1544455 /mnt/data/home/pim/.minecraft/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
java    13596  pim    9r  VREG  3863829994,528604845     5111 1543009 /mnt/data/home/pim/.minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
java    13596  pim   10r  VREG  3863829994,528604845    78175 1540316 /mnt/data/home/pim/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
java    13596  pim   11r  VREG  3863829994,528604845  3823147 1540331 /mnt/data/home/pim/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
java    13596  pim   12r  VREG  3863829994,528604845  2521113 1540284 /mnt/data/home/pim/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
java    13596  pim   13r  VREG  3863829994,528604845   479881 1540348 /mnt/data/home/pim/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
java    13596  pim   14r  VREG  3863829994,528604845   208700 1540288 /mnt/data/home/pim/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
java    13596  pim   15r  VREG  3863829994,528604845   284184 1540286 /mnt/data/home/pim/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
java    13596  pim   16r  VREG  3863829994,528604845   208338 1540363 /mnt/data/home/pim/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
java    13596  pim   17r  VREG  3863829994,528604845     7508 1540343 /mnt/data/home/pim/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
java    13596  pim   18r  VREG  3863829994,528604845    77392 1543000 /mnt/data/home/pim/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
java    13596  pim   19r  VREG  3863829994,528604845   673183 1475523 /mnt/data/home/pim/.minecraft/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
java    13596  pim   20r  VREG  3863829994,528604845   231952 1540321 /mnt/data/home/pim/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
java    13596  pim   21r  VREG  3863829994,528604845    70197 1544452 /mnt/data/home/pim/.minecraft/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
java    13596  pim   22r  VREG  3863829994,528604845   365552 1540377 /mnt/data/home/pim/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
java    13596  pim   23r  VREG  3863829994,528604845   589512 1540293 /mnt/data/home/pim/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
java    13596  pim   24r  VREG  3863829994,528604845    62050 1540376 /mnt/data/home/pim/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
java    13596  pim   25r  VREG  3863829994,528604845   282269 1540289 /mnt/data/home/pim/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
java    13596  pim   26r  VREG  3863829994,528604845 18800417 1540313 /mnt/data/home/pim/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
java    13596  pim   27r  VREG  3863829994,528604845   228859 1540369 /mnt/data/home/pim/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
java    13596  pim   28r  VREG  3863829994,528604845  1402925 1540315 /mnt/data/home/pim/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
java    13596  pim   29r  VREG  3863829994,528604845   309265 1517051 /mnt/data/home/pim/local/java/lwjgl3-port/lwjgl3/bin/RELEASE/lwjgl/lwjgl.jar
java    13596  pim   30r  VREG  3863829994,528604845    37337 1518023 /mnt/data/home/pim/local/java/lwjgl3-port/lwjgl3/bin/RELEASE/lwjgl-jemalloc/lwjgl-jemalloc.jar
java    13596  pim   31r  VREG  3863829994,528604845    78978 1518632 /mnt/data/home/pim/local/java/lwjgl3-port/lwjgl3/bin/RELEASE/lwjgl-openal/lwjgl-openal.jar
java    13596  pim   32r  VREG  3863829994,528604845   930526 1519073 /mnt/data/home/pim/local/java/lwjgl3-port/lwjgl3/bin/RELEASE/lwjgl-opengl/lwjgl-opengl.jar
java    13596  pim   33r  VREG  3863829994,528604845   115256 1517686 /mnt/data/home/pim/local/java/lwjgl3-port/lwjgl3/bin/RELEASE/lwjgl-glfw/lwjgl-glfw.jar
java    13596  pim   34r  VREG  3863829994,528604845   104661 1520075 /mnt/data/home/pim/local/java/lwjgl3-port/lwjgl3/bin/RELEASE/lwjgl-stb/lwjgl-stb.jar
java    13596  pim   35r  VREG  3863829994,528604845     7092 1542989 /mnt/data/home/pim/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
java    13596  pim   36r  VREG  3863829994,528604845    13164 1543038 /mnt/data/home/pim/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
java    13596  pim   37r  VREG  3863829994,528604845 17505781 1446534 /mnt/data/home/pim/.minecraft/versions/1.16.3/1.16.3.jar
java    13596  pim   38r  VREG 1391721247,4214480561   702573  366502 /usr/local/openjdk8/jre/lib/jsse.jar
java    13596  pim   39r  VCHR                   0,5      0t0       5 /dev/fd/2
java    13596  pim   40r  VCHR                   0,5   0t5396       5 /dev/fd/2
java    13596  pim   41r  VCHR                   0,5      0t0       5 /dev/fd/2
java    13596  pim   42r  VCHR                   0,5      0t0       5 /dev/fd/2
java    13596  pim   43r  VCHR                   0,5      0t0       5 /dev/fd/2
java    13596  pim   44r  VCHR                   0,5      0t0       5 /dev/fd/2
java    13596  pim   45r  VREG 1391721247,4214480561    96536  366501 /usr/local/openjdk8/jre/lib/jce.jar
java    13596  pim   46r  VREG 1391721247,4214480561  2033828  366463 /usr/local/openjdk8/jre/lib/ext/nashorn.jar
java    13596  pim   47u  VREG  3863829994,528604845     1288 1913729 /mnt/data/home/pim (data/home/pim)
java    13596  pim   48r  VREG 1391721247,4214480561    69400  366467 /usr/local/openjdk8/jre/lib/ext/zipfs.jar
java    13596  pim   49r  VREG  3863829994,528604845 17505781 1446534 /mnt/data/home/pim/.minecraft/versions/1.16.3/1.16.3.jar
java    13596  pim   50u  unix    0xfffff8024f992000      0t0         ->(none)
java    13596  pim   51r  VREG 1391721247,4214480561  3509714  366515 /usr/local/openjdk8/jre/lib/resources.jar
java    13596  pim   52u  unix    0xfffff807e2865000      0t0         ->0xfffff80184354368
java    13596  pim   53u                                              0xfffff8018b536f50 file struct, ty=11, op=0xffffffff831d6e78
java    13596  pim   54u                                              0xfffff8018b536f50 file struct, ty=11, op=0xffffffff831d6e78
java    13596  pim   55u  PIPE    0xfffff8044cc55000    16384         ->0xfffff8044cc55168
java    13596  pim   56r  VREG 1391721247,4214480561    55975  366464 /usr/local/openjdk8/jre/lib/ext/sunec.jar
java    13596  pim   57u  IPv6    0xfffff807ebd037a0      0t0     TCP 82.69.172.110.ip.spacesurfer.com:15830->[::52.167.72.167]:https (ESTABLISHED)
java    13596  pim   60u  PIPE    0xfffff8044cc55168        0         ->0xfffff8044cc55000
java    13596  pim   61u  unix    0xfffff803b9bac6d0      0t0         ->0xfffff804a87a86d0
java    13596  pim   62r  VREG  3863829994,528604845  1724614 1540766 /mnt/data/home/pim/.minecraft/assets/objects/87/87722a59c8d488370f3d430cd4c97a3161081785
java    13596  pim   64r  VREG 1391721247,4214480561  3861295  366458 /usr/local/openjdk8/jre/lib/ext/cldrdata.jar
java    13596  pim   65r  VREG 1391721247,4214480561  1182823  366461 /usr/local/openjdk8/jre/lib/ext/localedata.jar
java    13596  pim   66u  unix    0xfffff805af915a38      0t0         ->(none)
java    13596  pim   67r  VREG 1391721247,4214480561   271119  366465 /usr/local/openjdk8/jre/lib/ext/sunjce_provider.jar

**Pull request closed without merging**
